name: my first workflow

on:
     push:
        branches: [main]

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo
              uses: actions/checkout@v5


            - name: list and read files
              run: |
                echo "this is my first workflow"
                ls -lstr
                cat README.md

            - name: third party content(create ascii cow words)
              run: cowsay -f dragon "Run for cover, I am a Dragon.....Drawer" >> dragon.txt
              
              
            - name: another sample
              run:  echo "$(hostname)"
            
           
            - name: another sample
              run: echo "$(date)"

