name: my first workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps: 
            - name: welcome meassage
              run: echo "this is my first workflow"
              
            - name: another sample
              run:  echo "$(hostname)"
            
            - name: another sample
              run: echo "$(date)"

              