name: my first workflow

on:
     push:
        branches: [main]

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps: 
            - name: checkout repo
              uses: actions/checkout@v5


            - name: list and read files
              run: |
                echo "this is my first workflow"
                ls -lstr
                cat README.md

            - name: install npm command
              run: sudo apt-get install cowsay -y

            - name: add permission
              run: chmod +x script.sh

            - name: third party content(create ascii cow words)
              run: |
                ./script.sh
                

              
              
            - name: another sample
              run:  echo "$(hostname)"
            
           
            - name: another sample
              run: echo "$(date)"

